// examples/templates/vue-vue/host/src/pages/UtilsDemo.vue
<template>
  <div>
    <h2>普通 TS 模块调用</h2>
    <p>调用 vue-remote 暴露的 <code>./utils</code> 模块（loadRemote 返回模块命名空间，显式调用其导出）：</p>
    <p v-if="error" data-testid="demo-utils-error" style="color: #c45656">调用失败：{{ error }}</p>
    <ul v-else-if="result" data-testid="demo-utils-result">
      <li>sumNumbers(2, 3, 7) = {{ result.sum }}</li>
      <li>DEMO_ANSWER = {{ result.answer }}</li>
      <li>formatPrice(12.5) = {{ result.price }}</li>
    </ul>
    <p v-else>加载中…</p>
    <button data-testid="demo-utils-reload" @click="load">重新调用</button>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { loadRemote } from '@fulgurjs/federation/runtime'

// 普通 TS 模块同样走 loadRemote：类型来自插件同步的远程声明（src/fulgurjs/types），
// 入口字符串拼错会在编译期报错——不再需要手写接口或手动泛型

const result = ref<{ sum: number; answer: number; price: string } | null>(null)
const error = ref('')

async function load(): Promise<void> {
  error.value = ''
  try {
    const utils = await loadRemote('vue-remote/utils')
    result.value = {
      sum: utils.sumNumbers(2, 3, 7),
      answer: utils.DEMO_ANSWER,
      price: utils.formatPrice(12.5),
    }
  } catch (e) {
    error.value = String((e as Error)?.message ?? e)
  }
}

onMounted(load)
</script>

// templates/react-react/host/src/pages/UtilsDemo.tsx
import type { ReactNode } from 'react'
import { useLoadRemote } from '@fulgurjs/federation/react'

interface RemoteUtils {
  DEMO_ANSWER: number
  sumNumbers: (...numbers: number[]) => number
  formatPrice: (yuan: number) => string
}

/** 普通 TS 模块调用演示：useLoadRemote 返回模块命名空间（loading/error/reload 内置） */
export default function UtilsDemo(): ReactNode {
  const { data, error, loading, reload } = useLoadRemote<RemoteUtils>('react-remote/utils')
  return (
    <div style={{ fontFamily: 'sans-serif', padding: 16 }}>
      <h2>普通 TS 模块调用</h2>
      {error ? (
        <p data-testid="demo-utils-error" style={{ color: '#c45656' }}>
          调用失败：{String((error as Error)?.message ?? error)}
        </p>
      ) : loading || !data ? (
        <p>加载中…</p>
      ) : (
        <ul data-testid="demo-utils-result">
          <li>sumNumbers(2, 3, 7) = {data.sumNumbers(2, 3, 7)}</li>
          <li>DEMO_ANSWER = {data.DEMO_ANSWER}</li>
          <li>formatPrice(12.5) = {data.formatPrice(12.5)}</li>
        </ul>
      )}
      <button data-testid="demo-utils-reload" onClick={() => void reload()}>重新调用</button>
    </div>
  )
}
